name: HerokuContainer
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: ls
    - run: ls walmart-ahenriquez.Web/
    - run: pwd
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Build .NET Core
      run: dotnet build
    - name: Tests .NET Core
      run: dotnet test --logger trx
    - name: Build and deploy the Docker image
      env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ 'walmart-ahenriquez' }}
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME